### ISSUE TITLE
Cannot build demo-2 slides with the right arrow 

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/KTH-Library.github.io#1]
Would it be possible to use fontawesome and "fa-right-arrow" instead?

Or how can I install whatever is needed for the right arrow used right now?

` $\rightarrow$` doesn't work for me?

**Comment by agnepagne** [comment]
`$\rightarrow$` is LaTeX code, and works out of the box for me. It may work to just install `texlive-full`, which seems to be the standard LaTeX package for Linux.

**Comment by mskyttner** [comment]
Would like to not add this (big) package, could a fontawesome icon be used instead?

**Comment by agnepagne** [comment]
Fixed in 042560577014d05bc07236872d3cabaa519518b2
